### ISSUE TITLE
Question for STORNModel inputs

### ISSUE THREAD

**Issue by pidipidi** [durner/STORN-keras#1]
Hello, 
I am wondering to know the type and shape of inputs for STORNModel. I simply input (n_sample, seq_len, dim) data to 'inputs' and 'target', but I got errors. It looks the inputs should be a list of some numpy arrays. Its slightly difficult to analyze what the desired type and shape of inputs from the code. Could you tell me what can be the structure of inputs and target in fit function?

Ex)
m = STORNModel() 
m.fit(inputs, target)

**Comment by durner** [comment]
The network requires always also the previous inputs as defined in the paper.

Here an example:
```
inputs = [train_x_next, train_x_prev]
storn = STORNModel(activation='tanh', n_deep=6, with_trending_prior=True, latent_dim=32, n_hidden_dense=64)
target = train_x_next
storn.fit(inputs, target, max_epochs=400)
```
