### ISSUE TITLE
Need data to train and evaluate

### ISSUE THREAD

**Issue by xray1111** [durner/STORN-keras#2]
Great job! 
I'm very interested in the project and I'd like to make it run on my PC, but I don't have a Baxter robot, and can not generate the time series data. Could you please kindly upload a copy of the data? Thanks!

**Comment by durner** [comment]
Hi xray1111, unfortunately I cannot send you any test files. We got them from a research institute to test the effectiveness of such a stochastic rnn but are not allowed to publish the raw data.
